.github/workflows/ci.yaml:
  schedule: false
  env:
    - DOCKER_IMAGE: adorsys/origin-web-console
      TAG: latest
      DIR: origin-web-console
    - DOCKER_IMAGE: adorsys/origin-haproxy-router
      TAG: latest
      DIR: origin-haproxy-router

.gitignore:
  paths:
    - 'origin-haproxy-router/contrib/haproxy-*'
    - 'origin-haproxy-router/contrib/*.template'
