---
name: Search for updates

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 1 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure git updates
        run: |
          git config --global user.name 'adorsys GmbH & Co. KG'
          git config --global user.email 'adorsysoss@users.noreply.github.com'

      - run: ./contrib/update-images.sh
      - run: git push
